# Generated by Django 5.0.2 on 2024-11-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_task',
            name='number',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
