# Generated by Django 5.0.2 on 2024-11-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_task', '0002_alter_login_task_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_task',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
